-- Run this in the Supabase SQL Editor after 003_edit_revision_kind.sql is
-- already applied. Foundation for Bucket List and Passport: Supabase Auth
-- (magic link — no separate users table needed, auth.users is the identity
-- source) plus the private, per-user tables both features save into, plus a
-- private Storage bucket for passport photos. No UI ships on top of this in
-- the same pass except the sign-in sheet — see src/AuthContext.jsx and
-- src/SignInSheet.jsx.
--
-- Search/generate stays fully anonymous: nothing here gates reading or
-- generating a trip. Auth only ever gates SAVING something to an account.

-- itineraries.owner was reserved as `text` with no auth system to populate
-- it yet (see schema.sql). Now that Supabase Auth exists, point it at
-- auth.users properly. Safe to run even though the column is currently
-- always null (nothing to cast) — guarded so re-running this file is a
-- no-op once already applied.
do $$
begin
  if (select data_type from information_schema.columns where table_name = 'itineraries' and column_name = 'owner') = 'text' then
    alter table itineraries alter column owner type uuid using owner::uuid;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'itineraries_owner_fkey'
  ) then
    -- on delete set null, not cascade: deleting an account must never delete
    -- a trip — including one someone else is relying on via a shared link.
    -- It just goes back to being an anonymous, ownerless row, exactly like
    -- any trip generated by a signed-out visitor.
    alter table itineraries
      add constraint itineraries_owner_fkey
      foreign key (owner) references auth.users(id) on delete set null;
  end if;
end $$;

create index if not exists itineraries_owner_idx on itineraries (owner);

-- ---------------------------------------------------------------------------
-- Bucket List
-- ---------------------------------------------------------------------------

create table if not exists bucket_lists (
  id uuid primary key default gen_random_uuid(),
  owner uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create index if not exists bucket_lists_owner_idx on bucket_lists (owner);

alter table bucket_lists enable row level security;

drop policy if exists "bucket_lists select own" on bucket_lists;
create policy "bucket_lists select own" on bucket_lists for select using (owner = auth.uid());
drop policy if exists "bucket_lists insert own" on bucket_lists;
create policy "bucket_lists insert own" on bucket_lists for insert with check (owner = auth.uid());
drop policy if exists "bucket_lists update own" on bucket_lists;
create policy "bucket_lists update own" on bucket_lists for update using (owner = auth.uid()) with check (owner = auth.uid());
drop policy if exists "bucket_lists delete own" on bucket_lists;
create policy "bucket_lists delete own" on bucket_lists for delete using (owner = auth.uid());

-- No owner column here on purpose — ownership is via the parent list, one
-- hop away, exactly like passport_photos below. Keeping it off avoids a
-- second place a row's ownership could ever drift out of sync with its
-- parent.
create table if not exists bucket_list_items (
  id uuid primary key default gen_random_uuid(),
  list_id uuid not null references bucket_lists(id) on delete cascade,
  place_name text not null,
  city text,
  country text,
  lat double precision,
  lng double precision,
  -- Matches geocodeCacheKey(searchName, name, targetCityName, countryCode)
  -- from api/_lib/geocode.js — the same place-identity key the itinerary
  -- pipeline (and creator_clips) resolves a real-world location to, so a
  -- bucket-list entry can be matched against an itinerary stop without a
  -- second, separate normalization scheme to keep in sync by hand.
  place_key text,
  note text,
  added_at timestamptz not null default now()
);

create index if not exists bucket_list_items_list_id_idx on bucket_list_items (list_id);
create index if not exists bucket_list_items_place_key_idx on bucket_list_items (place_key);

alter table bucket_list_items enable row level security;

drop policy if exists "bucket_list_items select own" on bucket_list_items;
create policy "bucket_list_items select own" on bucket_list_items for select using (
  list_id in (select id from bucket_lists where owner = auth.uid())
);
drop policy if exists "bucket_list_items insert own" on bucket_list_items;
create policy "bucket_list_items insert own" on bucket_list_items for insert with check (
  list_id in (select id from bucket_lists where owner = auth.uid())
);
drop policy if exists "bucket_list_items update own" on bucket_list_items;
create policy "bucket_list_items update own" on bucket_list_items for update using (
  list_id in (select id from bucket_lists where owner = auth.uid())
) with check (
  list_id in (select id from bucket_lists where owner = auth.uid())
);
drop policy if exists "bucket_list_items delete own" on bucket_list_items;
create policy "bucket_list_items delete own" on bucket_list_items for delete using (
  list_id in (select id from bucket_lists where owner = auth.uid())
);

-- ---------------------------------------------------------------------------
-- Passport
-- ---------------------------------------------------------------------------

create table if not exists passport_entries (
  id uuid primary key default gen_random_uuid(),
  owner uuid not null references auth.users(id) on delete cascade,
  place_name text not null,
  city text,
  country text,
  lat double precision,
  lng double precision,
  visited_on date,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists passport_entries_owner_idx on passport_entries (owner);

alter table passport_entries enable row level security;

drop policy if exists "passport_entries select own" on passport_entries;
create policy "passport_entries select own" on passport_entries for select using (owner = auth.uid());
drop policy if exists "passport_entries insert own" on passport_entries;
create policy "passport_entries insert own" on passport_entries for insert with check (owner = auth.uid());
drop policy if exists "passport_entries update own" on passport_entries;
create policy "passport_entries update own" on passport_entries for update using (owner = auth.uid()) with check (owner = auth.uid());
drop policy if exists "passport_entries delete own" on passport_entries;
create policy "passport_entries delete own" on passport_entries for delete using (owner = auth.uid());

create table if not exists passport_photos (
  id uuid primary key default gen_random_uuid(),
  entry_id uuid not null references passport_entries(id) on delete cascade,
  storage_path text not null,
  created_at timestamptz not null default now()
);

create index if not exists passport_photos_entry_id_idx on passport_photos (entry_id);

alter table passport_photos enable row level security;

drop policy if exists "passport_photos select own" on passport_photos;
create policy "passport_photos select own" on passport_photos for select using (
  entry_id in (select id from passport_entries where owner = auth.uid())
);
drop policy if exists "passport_photos insert own" on passport_photos;
create policy "passport_photos insert own" on passport_photos for insert with check (
  entry_id in (select id from passport_entries where owner = auth.uid())
);
drop policy if exists "passport_photos update own" on passport_photos;
create policy "passport_photos update own" on passport_photos for update using (
  entry_id in (select id from passport_entries where owner = auth.uid())
) with check (
  entry_id in (select id from passport_entries where owner = auth.uid())
);
drop policy if exists "passport_photos delete own" on passport_photos;
create policy "passport_photos delete own" on passport_photos for delete using (
  entry_id in (select id from passport_entries where owner = auth.uid())
);

-- ---------------------------------------------------------------------------
-- Storage — passport photos
-- ---------------------------------------------------------------------------

-- Private bucket: RLS on storage.objects (below) is what actually restricts
-- access, but public=false also blocks the unauthenticated public-URL path
-- entirely, so a leaked object path alone is never enough to view a photo.
insert into storage.buckets (id, name, public)
values ('passport-photos', 'passport-photos', false)
on conflict (id) do nothing;

-- Upload path convention: <user_id>/<filename> — storage.foldername(name)
-- splits the object path on "/" and returns the folder segments, so
-- (storage.foldername(name))[1] is that leading <user_id> segment. A user
-- can only touch objects under their own folder; nobody can list or read
-- another user's photos, matching the private-by-default posture on the
-- tables above (unlike creator_clips, which is deliberately public).
drop policy if exists "passport photos select own" on storage.objects;
create policy "passport photos select own" on storage.objects for select using (
  bucket_id = 'passport-photos' and (storage.foldername(name))[1] = auth.uid()::text
);
drop policy if exists "passport photos insert own" on storage.objects;
create policy "passport photos insert own" on storage.objects for insert with check (
  bucket_id = 'passport-photos' and (storage.foldername(name))[1] = auth.uid()::text
);
drop policy if exists "passport photos update own" on storage.objects;
create policy "passport photos update own" on storage.objects for update using (
  bucket_id = 'passport-photos' and (storage.foldername(name))[1] = auth.uid()::text
);
drop policy if exists "passport photos delete own" on storage.objects;
create policy "passport photos delete own" on storage.objects for delete using (
  bucket_id = 'passport-photos' and (storage.foldername(name))[1] = auth.uid()::text
);
